#!/bin/bash

# Copyright (c) 2015 Ryan Kerr
# This file is licensed under GPLv3

# Runs the testing class for swiftdrive using the
# java binaries rather than the runnable jar file

PROJECT_PATH="/data/swiftspace/swiftdrive"

pushd $PROJECT_PATH/bin
	java sd/swiftglobal/rk/SwiftTest "$@"
popd
